#!/usr/bin/env python3
"""Generate runtime adapters from canonical plugin and agent sources."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
PORTABLE_FIELDS = ("name", "version", "description", "author", "license", "keywords")
CODEX_AGENT_HEADER = "# Generated by scripts/generate_adapters.py. Do not edit.\n"


def read_agent(path: Path) -> tuple[str, str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"\A---\n(?P<frontmatter>.*?)\n---\n(?P<body>.*)\Z", text, re.DOTALL)
    if match is None:
        raise ValueError(f"{path}: missing YAML frontmatter")

    fields: dict[str, str] = {}
    for line in match.group("frontmatter").splitlines():
        key, separator, value = line.partition(":")
        if separator:
            fields[key.strip()] = value.strip()

    name = fields.get("name", "")
    description = fields.get("description", "")
    if not name or not description:
        raise ValueError(f"{path}: name and description are required")

    return name, description, match.group("body").strip()


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def expected_files(root: Path = ROOT) -> dict[Path, str]:
    manifest = json.loads((root / "plugin.json").read_text(encoding="utf-8"))
    identity = {field: manifest[field] for field in PORTABLE_FIELDS if field in manifest}
    interface = manifest["extensions"]["com.openai"]["interface"]

    codex_manifest = dict(identity)
    codex_manifest["skills"] = "./skills/"
    codex_interface = dict(interface)
    default_prompts = codex_interface.get("defaultPrompt", [])
    if isinstance(default_prompts, list):
        codex_interface["defaultPrompt"] = default_prompts[0] if default_prompts else "Use Senior Engineering."
    codex_manifest["interface"] = codex_interface

    files = {
        root / ".codex-plugin" / "plugin.json": json.dumps(codex_manifest, indent=2, ensure_ascii=False) + "\n",
    }

    for source in sorted((root / "agents").glob("*.md")):
        name, description, body = read_agent(source)
        if source.stem != name:
            raise ValueError(f"{source}: filename must match agent name {name!r}")
        if '"""' in body:
            raise ValueError(f"{source}: body cannot contain TOML triple quotes")
        files[root / ".codex" / "agents" / f"{name}.toml"] = (
            CODEX_AGENT_HEADER
            +
            f"name = {toml_string(name)}\n"
            f"description = {toml_string(description)}\n"
            'sandbox_mode = "read-only"\n'
            f'developer_instructions = """\n{body}\n"""\n'
        )

    return files


def find_orphans(expected: set[Path], root: Path = ROOT) -> list[Path]:
    managed_roots = (
        root / ".codex-plugin",
        root / ".codex" / "agents",
    )
    return sorted(
        path
        for managed_root in managed_roots
        if managed_root.exists()
        for path in managed_root.rglob("*")
        if path.is_file() and path not in expected
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when generated adapters are stale.")
    args = parser.parse_args()

    generated = expected_files()
    orphans = find_orphans(set(generated))
    if orphans:
        print("unexpected files in generated adapter directories:", file=sys.stderr)
        for path in orphans:
            print(f"- {path.relative_to(ROOT)}", file=sys.stderr)
        print("remove or relocate them explicitly before regenerating", file=sys.stderr)
        return 1

    stale: list[str] = []
    for path, expected in generated.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == expected:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
        print(f"generated {path.relative_to(ROOT)}")

    if stale:
        print("stale generated adapters:", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        return 1

    if args.check:
        print("generated adapters are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
